name: Deploy hello-app to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  CLUSTER_NAME: hello-app-cluster
  WORKLOAD_IDENTITY_PROVIDER: projects/409164299281/locations/global/workloadIdentityPools/github/providers/cloud-run-hello-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
        env:
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.REGION }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.REGION }}


#      - name: Setup gcloud
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          project_id: ${{ env.PROJECT_ID }}
##          service_account_key: ${{ secrets.GCP_SA_KEY }}
##          export_default_credentials: true
#
#      - name: Terraform Init
#        run: terraform init
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve -var="project_id=${{ env.PROJECT_ID }}"
#
#      - name: Get Credentials
#        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }}
#
#      - name: Deploy Application
#        run: |
#          kubectl apply -f kubernetes/deployment.yaml
#          kubectl apply -f kubernetes/service.yaml